### ISSUE TITLE
How to warm start the FirstOrderLp.jl solver?

### ISSUE THREAD

**Issue by ZedongPeng** [google-research/FirstOrderLp.jl#105]
## Expected Behavior
Can we set a starting point for in the FirstOrderLp.jl solver? Or warm-start the dual variables?

In the paper, it's mentioned that 
> All first-order methods use all-zero vectors as the initial starting points.

**Comment by mlubin** [comment]
The primal and dual starting points are initialized to zero [here](https://github.com/google-research/FirstOrderLp.jl/blob/e47740b7ba349185efde7e3bb872ca6021c9bfc4/src/primal_dual_hybrid_gradient.jl#L806-L810). You'll need to modify the code to set a different starting point (`current_primal_solution` and `current_dual_solution`). If you do this, also be sure to set `current_dual_product` to `constraint_matrix' * current_dual_solution`.

How will you select the starting points?

**Comment by ZedongPeng** [comment]
Hi Lubin. Thanks for your reply and sorry for the late response. I am trying to solve a large-scale bidding optimization model. The model needs to be solved repeatedly thousands of times every day(with different input data). Since the formulation of the model is deterministic and only the input data will change, I am thinking about using ML or RL to obtain a good start point.

**Comment by mlubin** [comment]
It seems like you're trying to use this code to do something useful, which was not intended :). However, I'm happy to say that a C++ implementation of the PDLP algorithm is now available in [OR-Tools](https://github.com/google/or-tools/blob/75a0a4ab8cf4e091c67d108e3404ea53a92925f7/ortools/pdlp/primal_dual_hybrid_gradient.h). This code supports initial starting points. I'll be happy to answer further questions on that repository.
