### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by haihaolu** [google-research/FirstOrderLp.jl#109]
## Expected Behavior
No error should be raised when running the test.

## Actual Behavior
Test "restart_scheme=adaptive_localized" fails.

## Steps to Reproduce the Problem

1. Clone the directory and set up the environment
1. Running the tests by 
```shell
$ julia --color=yes --project -e 'import Pkg; Pkg.test("FirstOrderLp")'
```

## Specifications

- Version: Julia 1.7
- Platform: Mac

**Comment by dapplegate** [comment]
@ohinder commented (on the linked pull request) that he was unable to reproduce this problem.

Did you attempt to reproduce using Julia 1.7 on a Mac?

**Comment by ohinder** [comment]
ah ... I was using julia 1.8.3 when I switch to julia 1.7.1 the test fails
