### ISSUE TITLE
Small typo in code

### ISSUE THREAD

**Issue by xiqi98** [google-research/FirstOrderLp.jl#112]
https://github.com/google-research/FirstOrderLp.jl/blob/4ccab200d4247dec930754fa47e6517860dd45ec/src/primal_dual_hybrid_gradient.jl#L388

It appears to me that it should be
```julia
sqrt(epsilon * (k - 1))
```
in this line, according to Theorem 4.1(a) in the paper
https://pdfs.semanticscholar.org/2b2e/a941e55e5fa2ee9d8f4ff393c14482051143.pdf

Maybe this is a typo?

**Comment by mlubin** [comment]
CC @ohinder

**Comment by ohinder** [comment]
Yes, this is a typo. Thanks for catching it!

**Comment by dapplegate** [comment]
Reopening, just to track issue until pull request is merged.
