### ISSUE TITLE
Is QP in PDHG necessary?

### ISSUE THREAD

**Issue by TomasOberhuber** [google-research/FirstOrderLp.jl#123]
Hi, I have rather a question concerning the PDHG method.  In the paper 

https://proceedings.neurips.cc/paper/2021/file/a8fbbd3b11424ce032ba813493d95ad7-Paper.pdf

there is a projection on the set Y in (3). If I understand the code well, it is solved on this line 

https://github.com/google-research/FirstOrderLp.jl/blob/69dcc66a88be58031efca740a83c82c0bad13227/src/primal_dual_hybrid_gradient.jl#L491

leading to 

https://github.com/google-research/FirstOrderLp.jl/blob/69dcc66a88be58031efca740a83c82c0bad13227/src/saddle_point.jl#L110  

where a QP problem is solved. I do not understand why? Could I just make the elements y[0..m1] non-negative like it is in the primal problem with x, l and u?

Thanks a lot, Tomas.

**Comment by mlubin** [comment]
Why do you say a QP problem is solved in `project_dual!`:
```
dual[idx] = max(dual[idx], 0.0)
```
This is making the elements non-negative.

**Comment by TomasOberhuber** [comment]
Ok, I see. I am sorry, I was conffused with the lines

```
problem::QuadraticProgrammingProblem,
)
  for idx in inequality_range(problem)
```

I am a Julia newbie so I was not sure about the meaning. Thanks a lot.
