### ISSUE TITLE
Error when loading unpreprocessed lp benchmark files

### ISSUE THREAD

**Issue by mlubin** [google-research/FirstOrderLp.jl#73]
Some files (e.g., `16_n14`) have an OBJSENSE header that QPSReader doesn't know how to parse. Fortunately you can just delete the header as a workaround because it's a minimization problem.

**Comment by mlubin** [comment]
The OBJSENSE header is nominally supported (https://github.com/JuliaSmoothOptimizers/QPSReader.jl/blob/58c845af6d4ca5cdaf6be474334650840efae93c/src/readqps.jl#L173), so there may be something unusual going on.

**Comment by mlubin** [comment]
Possible fix at https://github.com/JuliaSmoothOptimizers/QPSReader.jl/pull/43

**Comment by ZedongPeng** [comment]
Hi lubin @mlubin . Is OBJSENSE header supported by FirstOrderLP.jl now? It failed in my test.

**Comment by mlubin** [comment]
https://github.com/google-research/FirstOrderLp.jl/pull/104 imports the latest version of `QPSReader` which should support `OBJSENSE`.
